### PR TITLE
Add Vuo to the "Software that Uses Qt" list

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by JesseTG** [comment]
Ngh.  Mac-only.  Why do you do this to me?  :P

But this fits the criteria, so in it goes!  Thanks for contributing.

**Comment by smokris** [comment]
Thanks, @JesseTG!

> Ngh. Mac-only. Why do you do this to me? :P

Touché.  (Vuo does have plans for [cross-platform support](https://vuo.org/platforms) though.)

**Comment by JesseTG** [comment]
What parts of it now forbid that?  Heavy dependence on macOS APIs?

**Comment by smokris** [comment]
> What parts of it now forbid that? Heavy dependence on macOS APIs?

Yeah, there are some deviations from cross-platform code in order to adhere to the macOS human interface guidelines.

But, mainly, the holdup is that there are a lot of moving parts to Vuo, all of which need to be addressed in order to port to a new platform.  One of Vuo's developers gives an overview [on this thread](https://vuo.org/comment/1738#comment-1738).

Vuo is a community-driven project, where people make feature requests and vote on them.  Porting to Linux is currently one of the [top-voted feature requests](https://vuo.org/feature-request), and porting to Windows isn't far behind.

**Pull request merged**
